// The control API a running `cswap auto` loop serves over a unix socket in
// the backup root. The TUI (and scripts) use it for presence, status, a
// live event feed, and to request an immediate tick.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: pkg/swapapi/swapapi.proto

package swapapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutoSwitchService_GetStatus_FullMethodName    = "/cswap.v1.AutoSwitchService/GetStatus"
	AutoSwitchService_StreamEvents_FullMethodName = "/cswap.v1.AutoSwitchService/StreamEvents"
	AutoSwitchService_Wake_FullMethodName         = "/cswap.v1.AutoSwitchService/Wake"
)

// AutoSwitchServiceClient is the client API for AutoSwitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutoSwitchServiceClient interface {
	// GetStatus reports the running engine's effective configuration.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// StreamEvents replays nothing and then follows the engine's event feed
	// until the client disconnects.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Wake cuts the engine's current sleep short, triggering a tick now.
	Wake(ctx context.Context, in *WakeRequest, opts ...grpc.CallOption) (*WakeResponse, error)
}

type autoSwitchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoSwitchServiceClient(cc grpc.ClientConnInterface) AutoSwitchServiceClient {
	return &autoSwitchServiceClient{cc}
}

func (c *autoSwitchServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AutoSwitchService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoSwitchServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AutoSwitchService_ServiceDesc.Streams[0], AutoSwitchService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AutoSwitchService_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *autoSwitchServiceClient) Wake(ctx context.Context, in *WakeRequest, opts ...grpc.CallOption) (*WakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeResponse)
	err := c.cc.Invoke(ctx, AutoSwitchService_Wake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoSwitchServiceServer is the server API for AutoSwitchService service.
// All implementations must embed UnimplementedAutoSwitchServiceServer
// for forward compatibility.
type AutoSwitchServiceServer interface {
	// GetStatus reports the running engine's effective configuration.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// StreamEvents replays nothing and then follows the engine's event feed
	// until the client disconnects.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	// Wake cuts the engine's current sleep short, triggering a tick now.
	Wake(context.Context, *WakeRequest) (*WakeResponse, error)
	mustEmbedUnimplementedAutoSwitchServiceServer()
}

// UnimplementedAutoSwitchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutoSwitchServiceServer struct{}

func (UnimplementedAutoSwitchServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAutoSwitchServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAutoSwitchServiceServer) Wake(context.Context, *WakeRequest) (*WakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wake not implemented")
}
func (UnimplementedAutoSwitchServiceServer) mustEmbedUnimplementedAutoSwitchServiceServer() {}
func (UnimplementedAutoSwitchServiceServer) testEmbeddedByValue()                           {}

// UnsafeAutoSwitchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutoSwitchServiceServer will
// result in compilation errors.
type UnsafeAutoSwitchServiceServer interface {
	mustEmbedUnimplementedAutoSwitchServiceServer()
}

func RegisterAutoSwitchServiceServer(s grpc.ServiceRegistrar, srv AutoSwitchServiceServer) {
	// If the following call panics, it indicates UnimplementedAutoSwitchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutoSwitchService_ServiceDesc, srv)
}

func _AutoSwitchService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoSwitchServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoSwitchService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoSwitchServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoSwitchService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AutoSwitchServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AutoSwitchService_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _AutoSwitchService_Wake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoSwitchServiceServer).Wake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutoSwitchService_Wake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoSwitchServiceServer).Wake(ctx, req.(*WakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutoSwitchService_ServiceDesc is the grpc.ServiceDesc for AutoSwitchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutoSwitchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cswap.v1.AutoSwitchService",
	HandlerType: (*AutoSwitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _AutoSwitchService_GetStatus_Handler,
		},
		{
			MethodName: "Wake",
			Handler:    _AutoSwitchService_Wake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _AutoSwitchService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/swapapi/swapapi.proto",
}
