// The control API a running `cswap auto` loop serves over a unix socket in
// the backup root. The TUI (and scripts) use it for presence, status, a
// live event feed, and to request an immediate tick.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/swapapi/swapapi.proto

package swapapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swapapi_swapapi_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DryRun          bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	ThresholdPct    float64                `protobuf:"fixed64,3,opt,name=threshold_pct,json=thresholdPct,proto3" json:"threshold_pct,omitempty"`
	IntervalSeconds float64                `protobuf:"fixed64,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	Strategy        string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	StartedAtUnix   int64                  `protobuf:"varint,6,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swapapi_swapapi_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *GetStatusResponse) GetThresholdPct() float64 {
	if x != nil {
		return x.ThresholdPct
	}
	return 0
}

func (x *GetStatusResponse) GetIntervalSeconds() float64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *GetStatusResponse) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swapapi_swapapi_proto_rawDescGZIP(), []int{2}
}

// Event mirrors the engine's JSONL event: kind plus the field payload as
// JSON, with the pre-rendered human line for display convenience.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	TsUnix        int64                  `protobuf:"varint,2,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Human         string                 `protobuf:"bytes,4,opt,name=human,proto3" json:"human,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_swapapi_swapapi_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

func (x *Event) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *Event) GetHuman() string {
	if x != nil {
		return x.Human
	}
	return ""
}

type WakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeRequest) Reset() {
	*x = WakeRequest{}
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeRequest) ProtoMessage() {}

func (x *WakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeRequest.ProtoReflect.Descriptor instead.
func (*WakeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_swapapi_swapapi_proto_rawDescGZIP(), []int{4}
}

type WakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Woken         bool                   `protobuf:"varint,1,opt,name=woken,proto3" json:"woken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeResponse) Reset() {
	*x = WakeResponse{}
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeResponse) ProtoMessage() {}

func (x *WakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_swapapi_swapapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeResponse.ProtoReflect.Descriptor instead.
func (*WakeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_swapapi_swapapi_proto_rawDescGZIP(), []int{5}
}

func (x *WakeResponse) GetWoken() bool {
	if x != nil {
		return x.Woken
	}
	return false
}

var File_pkg_swapapi_swapapi_proto protoreflect.FileDescriptor

const file_pkg_swapapi_swapapi_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/swapapi/swapapi.proto\x12\bcswap.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xda\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x12#\n" +
	"\rthreshold_pct\x18\x03 \x01(\x01R\fthresholdPct\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x01R\x0fintervalSeconds\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12&\n" +
	"\x0fstarted_at_unix\x18\x06 \x01(\x03R\rstartedAtUnix\"\x15\n" +
	"\x13StreamEventsRequest\"m\n" +
	"\x05Event\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\ats_unix\x18\x02 \x01(\x03R\x06tsUnix\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\x12\x14\n" +
	"\x05human\x18\x04 \x01(\tR\x05human\"\r\n" +
	"\vWakeRequest\"$\n" +
	"\fWakeResponse\x12\x14\n" +
	"\x05woken\x18\x01 \x01(\bR\x05woken2\xd2\x01\n" +
	"\x11AutoSwitchService\x12D\n" +
	"\tGetStatus\x12\x1a.cswap.v1.GetStatusRequest\x1a\x1b.cswap.v1.GetStatusResponse\x12@\n" +
	"\fStreamEvents\x12\x1d.cswap.v1.StreamEventsRequest\x1a\x0f.cswap.v1.Event0\x01\x125\n" +
	"\x04Wake\x12\x15.cswap.v1.WakeRequest\x1a\x16.cswap.v1.WakeResponseB0Z.github.com/blairham/go-claude-swap/pkg/swapapib\x06proto3"

var (
	file_pkg_swapapi_swapapi_proto_rawDescOnce sync.Once
	file_pkg_swapapi_swapapi_proto_rawDescData []byte
)

func file_pkg_swapapi_swapapi_proto_rawDescGZIP() []byte {
	file_pkg_swapapi_swapapi_proto_rawDescOnce.Do(func() {
		file_pkg_swapapi_swapapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_swapapi_swapapi_proto_rawDesc), len(file_pkg_swapapi_swapapi_proto_rawDesc)))
	})
	return file_pkg_swapapi_swapapi_proto_rawDescData
}

var file_pkg_swapapi_swapapi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_swapapi_swapapi_proto_goTypes = []any{
	(*GetStatusRequest)(nil),    // 0: cswap.v1.GetStatusRequest
	(*GetStatusResponse)(nil),   // 1: cswap.v1.GetStatusResponse
	(*StreamEventsRequest)(nil), // 2: cswap.v1.StreamEventsRequest
	(*Event)(nil),               // 3: cswap.v1.Event
	(*WakeRequest)(nil),         // 4: cswap.v1.WakeRequest
	(*WakeResponse)(nil),        // 5: cswap.v1.WakeResponse
}
var file_pkg_swapapi_swapapi_proto_depIdxs = []int32{
	0, // 0: cswap.v1.AutoSwitchService.GetStatus:input_type -> cswap.v1.GetStatusRequest
	2, // 1: cswap.v1.AutoSwitchService.StreamEvents:input_type -> cswap.v1.StreamEventsRequest
	4, // 2: cswap.v1.AutoSwitchService.Wake:input_type -> cswap.v1.WakeRequest
	1, // 3: cswap.v1.AutoSwitchService.GetStatus:output_type -> cswap.v1.GetStatusResponse
	3, // 4: cswap.v1.AutoSwitchService.StreamEvents:output_type -> cswap.v1.Event
	5, // 5: cswap.v1.AutoSwitchService.Wake:output_type -> cswap.v1.WakeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_swapapi_swapapi_proto_init() }
func file_pkg_swapapi_swapapi_proto_init() {
	if File_pkg_swapapi_swapapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_swapapi_swapapi_proto_rawDesc), len(file_pkg_swapapi_swapapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_swapapi_swapapi_proto_goTypes,
		DependencyIndexes: file_pkg_swapapi_swapapi_proto_depIdxs,
		MessageInfos:      file_pkg_swapapi_swapapi_proto_msgTypes,
	}.Build()
	File_pkg_swapapi_swapapi_proto = out.File
	file_pkg_swapapi_swapapi_proto_goTypes = nil
	file_pkg_swapapi_swapapi_proto_depIdxs = nil
}
